# Generated by Django 5.2.11 on 2026-03-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_aldo_owner_and_deactivation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inventory_i_invento_13392e_idx',
            old_name='inventory_i_invento_759f83_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inventory_i_movemen_76afde_idx',
            old_name='inventory_i_movemen_69457e_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorymovement',
            new_name='inventory_i_referen_0d8590_idx',
            old_name='inventory_i_referen_76d002_idx',
        ),
        migrations.RenameIndex(
            model_name='pricerecord',
            new_name='inventory_p_invento_9f1866_idx',
            old_name='inventory_p_invento_459db9_idx',
        ),
    ]
