# Generated by Django 5.2.11 on 2026-03-16 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='imageasset',
            new_name='images_imag_kind_d0e3e9_idx',
            old_name='images_imag_kind_76674e_idx',
        ),
        migrations.RenameIndex(
            model_name='imageasset',
            new_name='images_imag_sha256_d5563c_idx',
            old_name='images_imag_sha256_7b8eb9_idx',
        ),
    ]
