# Generated by Django 5.2.11 on 2026-03-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_imageasset_variant_and_group_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='imageasset',
            new_name='images_imag_kind_9e5229_idx',
            old_name='images_imag_kind_6b7579_idx',
        ),
    ]
