# Generated by Django 5.2.11 on 2026-03-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_brand_logo_and_rimspec_photo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='catalogitem',
            new_name='catalog_cat_item_ki_1d3096_idx',
            old_name='catalog_cat_item_7fa007_idx',
        ),
        migrations.RenameIndex(
            model_name='catalogitem',
            new_name='catalog_cat_code_98d37c_idx',
            old_name='catalog_cat_code_a43d41_idx',
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='origin',
            field=models.CharField(blank=True, choices=[('CHINA', 'China'), ('THAILAND', 'Thailand'), ('JAPAN', 'Japan'), ('KOREA', 'Korea'), ('AMERICAN', 'American'), ('INDIA', 'India'), ('MEXICAN', 'Mexican'), ('EUROPE', 'Europe'), ('PERUVIAN', 'Peruvian'), ('OTHER', 'Other')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='product_category',
            field=models.CharField(choices=[('TIRE', 'Tire'), ('RIM', 'Rim'), ('ACCESSORY', 'Accessory'), ('RIM_REPAIR', 'Rim Repair'), ('RIM_BALANCE', 'Rim Balance'), ('PAINTING', 'Painting'), ('TIRE_MOUNTING', 'Tire Mounting'), ('TIRE_PATCHING', 'Tire Patching'), ('SERVICE_GENERAL', 'General Service')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tirespec',
            name='letter_color',
            field=models.CharField(choices=[('BLACK', 'Black'), ('WHITE', 'White')], default='BLACK', max_length=16),
        ),
        migrations.AlterField(
            model_name='tirespec',
            name='ply_rating',
            field=models.CharField(choices=[('PR2', 'PR2'), ('PR4', 'PR4'), ('PR6', 'PR6'), ('PR8', 'PR8'), ('PR10', 'PR10'), ('PR12', 'PR12'), ('PR14', 'PR14'), ('PR16', 'PR16'), ('PR18', 'PR18'), ('PR20', 'PR20'), ('PR22', 'PR22')], max_length=4),
        ),
        migrations.AlterField(
            model_name='tirespec',
            name='tread_type',
            field=models.CharField(choices=[('LINEAR', 'Linear'), ('AT', 'A/T'), ('AT2', 'A/T 2'), ('AT3', 'A/T 3'), ('HT', 'H/T'), ('MT', 'M/T'), ('RT', 'R/T'), ('LT', 'L/T'), ('HIGHWAY', 'Highway'), ('SPORT', 'Sport'), ('MIXED', 'Mixed')], max_length=16),
        ),
    ]
