# Generated by Django 5.2.11 on 2026-03-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_migrate_legacy_images_to_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tirespec',
            name='tread_type',
            field=models.CharField(choices=[('LINEAR', 'Linear'), ('AT', 'A/T'), ('AT2', 'A/T 2'), ('AT3', 'A/T 3'), ('HT', 'H/T'), ('MT', 'M/T'), ('RT', 'R/T'), ('LT', 'L/T'), ('SPORT', 'Sport'), ('MIXED', 'Mixed')], max_length=16),
        ),
    ]
